Repository CCSI-Toolset/FOQUS, pull requests merged in 2018-09, with the labels that each got.

#279 OUU able to handle constraints
  foqus_lib/framework/ouu/OUU.py
  foqus_lib/gui/ouu/ouuSetupFrame.py
Labels: OUU

#278 Updated Install.md: Added links for downloading both the end-of-month release version and latest development version of FOQUS
  INSTALL.md
Labels: Installation

#282 Fixes issue #263. Error uploading csv files in UQ
  foqus_lib/framework/uq/LocalExecutionModule.py
Labels: UQ, bug :bomb:

#283 SSH Option and Readme Files for Tests
  INSTALL.md
  examples/Smoke Tests/README.md
  foqus_env_ssh.yml
  setup.py
  test/auto_test/README.md
  test/auto_test/foqus_setup_ssh.sh
Labels: Installation, enhancement
