Repository CCSI-Toolset/FOQUS, pull requests merged in 2018-08, with the labels that each got.

#260 Added reference to README
  README.md
Labels: enhancement

#267 README: Added link to PDF version of user's manual
  README.md
Labels: User Manual

#272 Smoke Tests Update
  examples/Smoke Tests/fs_smoke_test.py
  examples/Smoke Tests/ouu_smoke_test_ex_1.py
  examples/Smoke Tests/ouu_smoke_test_ex_2.py
  examples/Smoke Tests/ouu_smoke_test_ex_3.py
  examples/Smoke Tests/ouu_smoke_test_ex_4.py
  examples/Smoke Tests/ouu_smoke_test_ex_5.py
  examples/Smoke Tests/ouu_smoke_test_ex_6.py
  examples/Smoke Tests/ouu_smoke_test_ex_7.py
  examples/Smoke Tests/uq_smoke_test_data_analysis.py
  examples/Smoke Tests/uq_smoke_test_data_visualization.py
  examples/Smoke Tests/uq_smoke_test_inference.py
  examples/Smoke Tests/uq_smoke_test_input_importance.py
  examples/Smoke Tests/uq_smoke_test_polynomial.py
  examples/Smoke Tests/uq_smoke_test_response_surface_validation.py
  examples/Smoke Tests/uq_smoke_test_response_surface_visualization.py
  examples/Smoke Tests/uq_smoke_test_response_uq_analysis.py
Labels: Testing
