Repository CCSI-Toolset/FOQUS, pull requests merged in 2019-05, with the labels that each got.

#479 Fixing ouu
  foqus_lib/framework/ouu/OUU.py
Labels: OUU

#480 Documentation: Added instructions for updating Registry Keys in Windows
  docs/source/chapt_ouu/figs/Applications.jpg
  docs/source/chapt_ouu/figs/HKEY_CLASSES_ROOT.jpg
  docs/source/chapt_ouu/figs/Start_Menu.jpg
  docs/source/chapt_ouu/figs/py_auto_file.jpg
  docs/source/chapt_ouu/figs/python.jpg
  docs/source/chapt_ouu/reference.rst
Labels: Documentation, OUU

#478 Minor edit to Remote Turbine tutorial
  docs/source/chapt_flowsheet/tutorial/remote.rst
Labels: Documentation

#488 Updated OUU documentation: Types of variables
  docs/source/chapt_ouu/reference.rst
Labels: Documentation, OUU

#496 Fix doc warnings and remove heat integration docs
  docs/source/chapt_flowsheet/reference/flowsheet.rst
  docs/source/chapt_flowsheet/reference/getting_started.rst
  docs/source/chapt_flowsheet/reference/home.rst
  docs/source/chapt_flowsheet/tutorial/sim_flowsheet.rst
  docs/source/chapt_heat/figs/add_heat_int_tags.png
  docs/source/chapt_heat/figs/bfb_node_edit.png
  docs/source/chapt_heat/figs/edge_0_edit.png
  docs/source/chapt_heat/figs/edge_3_edit.png
  docs/source/chapt_heat/figs/edge_4_edit.png
  docs/source/chapt_heat/figs/edge_5_edit.png
  docs/source/chapt_heat/figs/edge_6_edit.png
  docs/source/chapt_heat/figs/flowsheet_heat_int.png
  docs/source/chapt_heat/figs/heat_int_inputs.png
  docs/source/chapt_heat/figs/heat_int_node_edit.png
  docs/source/chapt_heat/figs/heat_int_outputs.png
  docs/source/chapt_heat/figs/heat_int_results.png
  docs/source/chapt_heat/figs/heat_int_tags_bfb_1.png
  docs/source/chapt_heat/figs/heat_int_tags_bfb_2.png
  docs/source/chapt_heat/figs/heat_int_tags_bfb_3.png
  docs/source/chapt_heat/figs/heat_int_tags_comp_1.png
  docs/source/chapt_heat/figs/heat_int_tags_comp_2.png
  docs/source/chapt_heat/figs/heat_int_tags_comp_3.png
  docs/source/chapt_heat/figs/icon_1.png
  docs/source/chapt_heat/figs/icon_2.png
  docs/source/chapt_heat/figs/start_session.png
  docs/source/chapt_heat/figs/steam_cycle_inputs.png
  docs/source/chapt_heat/figs/steam_cycle_outputs.png
  docs/source/chapt_heat/figs/steam_cycle_results.png
  docs/source/chapt_heat/figs/total_cons_inputs.png
  docs/source/chapt_heat/figs/total_cons_outputs.png
  docs/source/chapt_heat/figs/total_cons_python.png
  docs/source/chapt_heat/figs/upload_model.png
  docs/source/chapt_heat/index.rst
  docs/source/chapt_heat/reference.rst
  docs/source/chapt_heat/tutorial.rst
  docs/source/chapt_intro/index.rst
  docs/source/chapt_opt/reference/optimization.rst
  docs/source/chapt_uq/tutorial/sim.rst
  docs/source/copyright.rst
  docs/source/index.rst
  foqus_lib/gui/main/mainWindow.py
Labels: Documentation

#501 Update sim.rst
  docs/source/chapt_uq/tutorial/sim.rst
Labels: Documentation, UQ

#505 Updated the links for the YouTube installation videos in README
  README.md
Labels: Documentation

#502 Fixing link for copyright.rst file
  docs/source/copyright.rst
Labels: Documentation
