Repository CCSI-Toolset/FOQUS, pull requests merged in 2019-10, with the labels that each got.

#586 Documentation updates
  docs/source/chapt_HI/tutorial/HI_test.rst
  docs/source/chapt_flowsheet/tutorial/data.rst
  docs/source/chapt_flowsheet/tutorial/files.rst
  docs/source/chapt_flowsheet/tutorial/recycle.rst
  docs/source/chapt_flowsheet/tutorial/remote.rst
  docs/source/chapt_flowsheet/tutorial/sim_flowsheet.rst
  docs/source/chapt_flowsheet/tutorial/simple_flowsheet.rst
  docs/source/chapt_opt/tutorial/parameter_est.rst
  docs/source/chapt_opt/tutorial/simple.rst
  docs/source/chapt_ouu/index.rst
  docs/source/chapt_ouu/tutorial.rst
  docs/source/chapt_pyomo/tutorial/index.rst
  docs/source/chapt_pyomo/tutorial/pyomo_test.rst
  docs/source/chapt_sdoe/index.rst
  docs/source/chapt_sinter/tutorial/acm.rst
  docs/source/chapt_sinter/tutorial/ap.rst
  docs/source/chapt_sinter/tutorial/excel.rst
  docs/source/chapt_sinter/tutorial/gproms.rst
  docs/source/chapt_sinter/tutorial/index.rst
  docs/source/chapt_surrogates/tutorial/acosso.rst
  docs/source/chapt_surrogates/tutorial/alamo.rst
  docs/source/chapt_surrogates/tutorial/bssanova.rst
  docs/source/chapt_surrogates/tutorial/flowsheet.rst
  docs/source/chapt_surrogates/tutorial/uq_model.rst
  docs/source/chapt_uq/index.rst
  docs/source/chapt_uq/tutorial/analysis.rst
  docs/source/chapt_uq/tutorial/data.rst
  docs/source/chapt_uq/tutorial/inf.rst
  docs/source/chapt_uq/tutorial/rs.rst
  docs/source/chapt_uq/tutorial/sim.rst
  docs/source/index.rst
Labels: Documentation

#589 Documentation: Fix link from Flowsheet tutorial to UQ tutorial
  docs/source/chapt_flowsheet/tutorial/data.rst
Labels: Documentation

#594 Fixing sip to latest version compatable with PyQt5 5.9
  requirements.txt
Labels: Priority:High

#596 Documentation: Update Optimization Parameter Estimation Tutorial
  docs/source/chapt_opt/figs/par_est_tut7.jpg
  docs/source/chapt_opt/figs/par_est_tut7.svg
  docs/source/chapt_opt/tutorial/parameter_est.rst
Labels: Documentation

#604 Adding CircleCI to FOQUS builds
  .circleci/config.yml
Labels: Testing

#595 WIP: Doc fixes
  docs/source/chapt_flowsheet/index.rst
  docs/source/chapt_opt/reference/optimization.rst
  docs/source/chapt_opt/tutorial/parameter_est.rst
  docs/source/chapt_uq/reference.rst
  docs/source/chapt_uq/tutorial/rs.rst
  docs/source/sphinx-build.log
Labels: Documentation, Priority:Mid

#609 New appveyor.xml file
  appveyor.yml
Labels: Testing
