Repository CCSI-Toolset/FOQUS, pull requests merged in 2019-01, with the labels that each got.

#337 pytest updates, results_s3_tests all pass
  cloud/aws/test/data/s3/foqus-sessions/anonymous/9f4def1c-d033-4761-9e8d-7ae979d230ae/03ce8184-3f2f-4445-9d4c-7141a28662e8/08e6bf2d-e6e2-4e75-8ce2-8e86a6a0db83.json
  cloud/aws/test/data/s3/foqus-sessions/anonymous/9f4def1c-d033-4761-9e8d-7ae979d230ae/03ce8184-3f2f-4445-9d4c-7141a28662e8/1.json
  foqus_lib/framework/graph/graph.py
  foqus_lib/framework/sampleResults/test/results_s3_test.py
Labels: Testing

#348 Updated Install/Instructions
  INSTALL.md
  foqus_lib/framework/gams/__init__.py
  foqus_lib/help/html/__init__.py
  foqus_lib/version/version.template
  setup.py
Labels: Installation, Python 3.x Compatibility

#354 Fixed optimization generate samples dialog.
  foqus_lib/framework/optimizer/problem.py
  foqus_lib/gui/optimization/optSampleGenDialog.py
  foqus_lib/gui/optimization/optSetupFrame.py
Labels: bug :bomb:

#353 Change Filter Method to Use Calculated Columns
  foqus_lib/framework/sampleResults/results.py
  foqus_lib/gui/flowsheet/dataFilterDialog.py
  foqus_lib/gui/flowsheet/dataFilterDialog_UI.ui
Labels: enhancement

#356 Simplify version module and use git descibe if available.
  foqus_lib/version/version.py
  foqus_lib/version/version.template
  setup.py
Labels: Installation, enhancement
