Repository CCSI-Toolset/FOQUS, pull requests merged in 2019-02, with the labels that each got.

#367 Fix turbine upload
  INSTALL.md
  examples/OUU/ouu_psuade_example/genX3sample.py
  foqus.py
  foqus_lib/framework/graph/graph.py
  foqus_lib/framework/session/session.py
  foqus_lib/framework/sim/turbineConfiguration.py
  foqus_lib/framework/sim/turbineLiteDB.py
  foqus_lib/gui/main/settingsFrame.py
  foqus_lib/gui/main/turbineConfig.py
  foqus_lib/gui/model/dmfUploadDialog.py
  foqus_lib/unit_test/turbineLiteTest.py
  requirments.txt
  setup.py
Labels: bug :bomb:

#379 fixing issue with creating directories in Windows OS
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
Labels: SDOE

#369 Adding Examples/SDOE directory with some example data
  examples/SDOE/candidate.csv
  examples/SDOE/historical_data.csv
Labels: SDOE

#382 few changes to sdoe framework and gui
  foqus_lib/framework/sdoe/candidate.pyc
  foqus_lib/framework/sdoe/distance.pyc
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
Labels: SDOE

#385 Fix edge panel
  foqus_lib/gui/flowsheet/edgePanel.py
Labels: bug :bomb:

#386 Adding a new sphinx make.bat file for windows.
  docs/make.bat
Labels: User Manual

#393 Documentation: Updated docs/source/index.rst
  docs/source/index.rst
Labels: Documentation

#395 Minor edits to chapt_intro/index
  docs/source/chapt_intro/index.rst
Labels: Documentation

#390 rename requirements.txt and fix type in conda create command
  INSTALL.md
  requirements.txt
Labels: Documentation

#402 Update to LocalExecutionModule.py, line 314
  foqus_lib/framework/uq/LocalExecutionModule.py
Labels: UQ, bug :bomb:

#403 Updated LocalExecutionModule.py, line 314
  foqus_lib/framework/uq/LocalExecutionModule.py
Labels: UQ, bug :bomb:

#404 Updated Install.md
  INSTALL.md
Labels: Documentation, Installation

#409 fixing path name
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
Labels: SDOE
