Repository CCSI-Toolset/FOQUS, pull requests merged in 2019-03, with the labels that each got.

#416 Updated ReadMe: New link for documentation and user's manual
  README.md
Labels: Documentation

#418 Updating SDOE documentation
  docs/source/chapt_sdoe/figs/1_home.png
  docs/source/chapt_sdoe/figs/2_preview_inputs.png
  docs/source/chapt_sdoe/figs/3_scatterplot_inputs.png
  docs/source/chapt_sdoe/figs/5_SDOE_page2.png
  docs/source/chapt_sdoe/figs/index.dat
  docs/source/chapt_sdoe/index.rst
Labels: Documentation, SDOE

#417 Updated ReadMe: Added instructions on how to create html version of documentation
  README.md
Labels: Documentation

#424 Adding a utility to write sinter config files
  foqus.py
  foqus_lib/gui/sinter/__init__.py
  foqus_lib/gui/sinter/sinter_config.py
  foqus_lib/gui/sinter/sinter_config.ui
  foqus_sinter_configure.py
Labels: enhancement

#425 New examples
  examples/Optimization/Opt_Test_02.foqus
  examples/Testing/ACM_Flash_Example.foqus
  examples/Testing/ACM_Flash_Example/Flash_Example.acmf
  examples/Testing/ACM_Flash_Example/Flash_Example_ACM.json
  examples/Testing/ACM_Flash_Example/Flash_Example_ACM_defaults.json
  examples/Testing/Aspen_Flash_Example.foqus
  examples/Testing/Aspen_Flash_Example/Flash_Example.bkp
  examples/Testing/Aspen_Flash_Example/Flash_Example_AP.json
  examples/Testing/Aspen_Flash_Example/Flash_Example_AP_defaults.json
  examples/Testing/Excel/SQRT_Test/testBook.json
  examples/Testing/Excel/SQRT_Test/testBook.xlsx
  examples/Testing/Excel/Test_01/MyExample.json
  examples/Testing/Excel/Test_01/MyExample.xlsx
  examples/Testing/README.md
Labels: Testing

#432 Add install instructions to sphinx docs.
  docs/source/chapt_flowsheet/reference/results.rst
  docs/source/chapt_install/index.rst
  docs/source/index.rst
  foqus_lib/gui/main/mainWindow.py
Labels: Documentation

#458 Fix a few bugs in deleting rows in data, empty sort list, and mystere…
  foqus_lib/framework/sampleResults/results.py
  foqus_lib/framework/surrogate/ALAMO.py
  foqus_lib/gui/flowsheet/dataBrowserFrame.py
  foqus_lib/gui/sinter/sinter_config.py
Labels: bug :bomb:
