Repository CCSI-Toolset/FOQUS, pull requests merged in 2019-12, with the labels that each got.

#649 Optimization Sample Var Data Format
  docs/source/chapt_opt/figs/optim_samplevars_csv.png
  docs/source/chapt_opt/tutorial/parameter_est.rst
Labels: Priority:Mid

#647 Fixing Unit Tests
  foqus_lib/framework/graph/nodeVars.py
  foqus_lib/unit_test/massBalance_test.py
  foqus_lib/unit_test/nodeVarListTest.py
  foqus_lib/unit_test/nodeVarList_test.py
  foqus_lib/unit_test/nodeVars_test.py
  foqus_lib/unit_test/turbineLite_test.py
Labels: Priority:Mid

#654 Uq analyze fix
  foqus_lib/framework/uq/Distribution.py
  foqus_lib/framework/uq/LocalExecutionModule.py
  foqus_lib/framework/uq/Model.py
  foqus_lib/framework/uq/SampleData.py
  foqus_lib/gui/uq/AnalysisDialog.py
Labels: Priority:High

#655 New documentation of SDoE module with description of process for the NUSF capability
  docs/source/chapt_sdoe/figs/0_design_overview.png
  docs/source/chapt_sdoe/figs/0_sdoe_sequence.png
  docs/source/chapt_sdoe/figs/10N_Test_SDOE.png
  docs/source/chapt_sdoe/figs/10N_Test_SDOE_choices.png
  docs/source/chapt_sdoe/figs/12N_completed_designs.png
  docs/source/chapt_sdoe/figs/1N_starting_screen.png
  docs/source/chapt_sdoe/figs/1U_starting_screen.png
  docs/source/chapt_sdoe/figs/1_starting_screen.png
  docs/source/chapt_sdoe/figs/3N_plot_candidates.png
  docs/source/chapt_sdoe/figs/4U_ensemble_aggregate.png
  docs/source/chapt_sdoe/figs/4_ensemble_aggregate.png
  docs/source/chapt_sdoe/figs/5N_second_window.png
  docs/source/chapt_sdoe/figs/5U_second_window.png
  docs/source/chapt_sdoe/figs/6U_after_test_SDOE.png
  docs/source/chapt_sdoe/figs/7U_completed_designs.png
  docs/source/chapt_sdoe/figs/9N_MWR_box.png
  docs/source/chapt_sdoe/figs/Ex1U_3_mM_choices.png
  docs/source/chapt_sdoe/index.rst
Labels: Documentation, SDOE

#652 Adding NUSF to SDoE
  appveyor.yml
  examples/SDOE/Candidate Points 8perc.csv
  examples/SDOE/SDOE_Ex1_Candidates.csv
  foqus_lib/framework/sdoe/df_utils.py
  foqus_lib/framework/sdoe/distance.py
  foqus_lib/framework/sdoe/nusf.py
  foqus_lib/framework/sdoe/order.py
  foqus_lib/framework/sdoe/plot_utils.py
  foqus_lib/framework/sdoe/sdoe.py
  foqus_lib/framework/sdoe/usf.py
  foqus_lib/gui/sdoe/SimSetup_UI.ui
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog_UI.ui
  foqus_lib/gui/sdoe/sdoePreview.py
  foqus_lib/gui/sdoe/sdoeSetupFrame.py
  foqus_lib/gui/sdoe/sdoeSetupFrame_UI.ui
  foqus_lib/gui/uq/SimSetup_UI.ui
  requirements.txt
Labels: Priority:High, SDOE

#657 Foqus gateway v2
  cloud/aws/README.md
Labels: Priority:Low

#658 Little SDOE doc fixes
  docs/source/chapt_sdoe/index.rst
Labels: Priority:Mid

#659 Re-org of SDOE chapter into separate files/sections
  docs/source/chapt_sdoe/basics.rst
  docs/source/chapt_sdoe/examples.rst
  docs/source/chapt_sdoe/index.rst
  docs/source/chapt_sdoe/overview.rst
Labels: Priority:Mid

#662 Breaking out the basics section into 2 files/sections
  docs/source/chapt_sdoe/basics-nonuniform.rst
  docs/source/chapt_sdoe/basics-uniform.rst
  docs/source/chapt_sdoe/basics.rst
Labels: Priority:Mid

#661 Removing duplicate files
  examples/SDOE/Candidate Points 8perc.csv
  examples/SDOE/SDOE_Ex1_Candidates.csv
Labels: Examples, Priority:Mid

#663 Last changes fixing NUSF code and plotting
  foqus_lib/framework/sdoe/distance.py
  foqus_lib/framework/sdoe/nusf.py
  foqus_lib/framework/sdoe/plot_utils.py
  foqus_lib/framework/sdoe/sdoe.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
  foqus_lib/gui/sdoe/sdoePreview.py
  foqus_lib/gui/sdoe/sdoeSetupFrame.py
  foqus_lib/gui/sdoe/sdoeSimSetup.py
Labels: SDOE
