Repository CCSI-Toolset/FOQUS, pull requests merged in 2019-09, with the labels that each got.

#562 Uploading SDoE tutorial files
  examples/SDOE/Candidate Points 8perc.csv
  examples/SDOE/SDOE_Ex1_Candidates.csv
Labels: Documentation, SDOE

#568 Issue#546
  foqus_lib/framework/uq/SampleData.py
  foqus_lib/gui/ouu/nodeToUQModel.py
Labels: OUU, Priority:Mid, bug :bomb:

#570 Documentation: Minor edit to the Flowsheet and Recycle section
  docs/source/chapt_flowsheet/tutorial/recycle.rst
Labels: Documentation

#572 Adding pytest & coverage via CircleCi
  .circleci/config.yml
  README.md
Labels: Priority:Mid

#576 Modifying Optimization Solver Descriptions
  foqus_lib/framework/optimizer/BFGS.py
  foqus_lib/framework/optimizer/NLopt.py
  foqus_lib/framework/optimizer/OptCMA.py
  foqus_lib/framework/optimizer/SLSQP.py
  foqus_lib/framework/optimizer/Snobfit.py
Labels: Priority:Mid

#575 Issue#482
  docs/source/chapt_ouu/reference.rst
  foqus_lib/gui/ouu/foqusPSUADEClient.bat
  foqus_lib/gui/ouu/ouuSetupFrame.py
Labels: OUU

#577 List of Publications
  docs/source/index.rst
Labels: Documentation, Priority:Mid

#582 Delete SolventFit from table of contents
  docs/source/chapt_solventfit/figs/SolventFitFig1.png
  docs/source/chapt_solventfit/figs/SolventFitFig2.png
  docs/source/chapt_solventfit/figs/SolventFitFig3.png
  docs/source/chapt_solventfit/figs/SolventFitFig4.png
  docs/source/chapt_solventfit/index.rst
  docs/source/chapt_solventfit/reference.rst
  docs/source/index.rst
Labels: Documentation, Priority:Low

#584 Fixing reference in alamo tutorial
  docs/source/chapt_surrogates/tutorial/alamo.rst
Labels: Priority:Low

#585 fix warnings in UQ data tutorial docs
  docs/source/chapt_uq/tutorial/data.rst
Labels: Priority:Low

#583 Fix doc warnings in sim_flowsheet.rst
  docs/source/chapt_flowsheet/tutorial/sim_flowsheet.rst
Labels: Priority:Low
