Repository CCSI-Toolset/FOQUS, pull requests merged in 2019-11, with the labels that each got.

#610 Missing self ref (pylint discovery)
  foqus_lib/framework/foqusOptions/option.py
Labels: Priority:Mid, Testing

#613 missing "self" in func defn
  foqus_lib/framework/foqusException/foqusException.py
Labels: Priority:Mid, Testing

#612 pylint errors in at_dict: bad super() call
  foqus_lib/framework/at_dict/at_dict.py
Labels: Priority:Mid, Testing

#606 Fixing cases in unit_test so pylint -E passes
  foqus_lib/unit_test/massBalanceTest.py
  foqus_lib/unit_test/nodeVarListTest.py
  foqus_lib/unit_test/nodeVarsTest.py
Labels: Priority:Mid, Testing

#611 pylint fixes in solventfit
  foqus_lib/framework/solventfit/SolventFit_testing.py
  foqus_lib/framework/solventfit/test_solventfit.py
Labels: Priority:Mid, Testing

#614 Pylint errors in framework/graph/
  foqus_lib/framework/graph/OptGraphOptim.py
  foqus_lib/framework/graph/graph.py
  foqus_lib/framework/graph/heatIntegration.py
  foqus_lib/framework/graph/nodeVars.py
Labels: Priority:Mid, Testing

#598 Foqus Cloud Update: Refactor foqus_service
  .circleci/config.yml
  cloud/aws/foqus_service.py
  cloud/aws/node/foqus-sns-update/index.js
  examples/test_files/OUU_Remote_Turbine_BFB/BFB_OUU_08_20_2019.foqus
  foqus_lib/framework/graph/graph.py
  foqus_lib/framework/session/session.py
  foqus_lib/framework/sim/process_management.py
  foqus_lib/framework/sim/turbineConfiguration.py
  foqus_lib/service/__init__.py
  foqus_lib/service/flowsheet.py
  foqus_lib/service/test/__init__.py
  foqus_lib/service/test/flowsheet_control_test.py
  requirements.txt
Labels: Priority:Mid

#617 Python 3.7.3 and PyQt5 5.13
  .circleci/config.yml
  appveyor.yml
  docs/source/chapt_install/index.rst
  requirements.txt
Labels: Priority:High

#619 Fixing issue #618
  foqus_lib/gui/ouu/ouuSetupFrame.ui
Labels: FOQUS GUI, OUU, Priority:High

#625 optimization gui fix
  foqus_lib/gui/optimization/optSetupFrame_UI.ui
Labels: Priority:Mid

#626 ALAMO stop button fixed
  foqus_lib/gui/surrogate/surrogateFrame.py
Labels: Priority:Mid

#629 Python 3.7.5
  .circleci/config.yml
  appveyor.yml
  docs/source/chapt_install/index.rst
Labels: Priority:High

#633 OUU in Optimization tab
  foqus_lib/framework/optimizer/problem.py
Labels: Priority:High

#644 Optimization Plot Change
  foqus_lib/framework/optimizer/NLopt.py
  foqus_lib/gui/optimization/optMonitor.py
Labels: Priority:High

#627 Optimization Traceback Messages Removed
  foqus_lib/framework/optimizer/optimization.py
Labels: Priority:Mid

#643 ALAMO SM Validation in UQ
  foqus_lib/framework/uq/Common.py
  foqus_lib/framework/uq/SurrogateParser.py
Labels: Priority:High
