Repository CCSI-Toolset/FOQUS, pull requests merged in 2019-06, with the labels that each got.

#516 Update README: Include new link for FOQUS usage guide videos
  README.md
Labels: Documentation

#520 Issue #519 correction
  docs/source/chapt_sinter/figs/ap/04_MetaDataFilled_upd.png
  docs/source/chapt_sinter/tutorial/ap.rst
Labels: Examples, SimSinter

#518 Replacing en dash with hyphen in command line examples
  docs/source/chapt_flowsheet/reference/settings.rst
  docs/source/chapt_install/index.rst
Labels: Documentation

#522 Added instructions on how to upload CSV file to automatically run a set of inputs
  docs/source/chapt_flowsheet/tutorial/simple_flowsheet.rst
  docs/source/chapt_uq/figs/tutorial/CSV_Upload.jpg
  docs/source/chapt_uq/figs/tutorial/Excel_Samples.jpg
  docs/source/chapt_uq/figs/tutorial/Flowsheet_Equations.jpg
  docs/source/chapt_uq/figs/tutorial/Flowsheet_Inputs.jpg
  docs/source/chapt_uq/figs/tutorial/Flowsheet_Outputs.jpg
  docs/source/chapt_uq/figs/tutorial/Flowsheet_Results.jpg
  docs/source/chapt_uq/figs/tutorial/Run_Samples.jpg
  docs/source/chapt_uq/figs/tutorial/Session_Tab.jpg
  docs/source/chapt_uq/figs/tutorial/UQ_Done.jpg
  docs/source/chapt_uq/figs/tutorial/UQ_Tab.jpg
  docs/source/chapt_uq/tutorial/sim.rst
Labels: Documentation

#524 Updated SDOE
  examples/SDOE/template_example.csv
  examples/UQ/Rosenbrock_no_vectors.foqus
  foqus_lib/framework/sampleResults/results.py
  foqus_lib/framework/sdoe/README
  foqus_lib/framework/sdoe/candidate.csv
  foqus_lib/framework/sdoe/config.ini
  foqus_lib/framework/sdoe/historical_data.csv
  foqus_lib/framework/sdoe/results/sdoe_candidates_8_100
  foqus_lib/framework/sdoe/results/sdoe_candidates_8_2000
  foqus_lib/framework/sdoe/results/sdoe_candidates_8_500
  foqus_lib/framework/sdoe/sdoe.out
  foqus_lib/framework/sdoe/sdoe.py
  foqus_lib/framework/session/session.py
  foqus_lib/framework/uq/ExperimentalDesign.py
  foqus_lib/gui/sdoe/SimSetup_UI.ui
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog_UI.ui
  foqus_lib/gui/sdoe/sdoePreview.py
  foqus_lib/gui/sdoe/sdoeSetupFrame.py
  foqus_lib/gui/sdoe/sdoeSetupFrame_UI.ui
  foqus_lib/gui/sdoe/sdoeSimSetup.py
  foqus_lib/gui/sdoe/updateSDOEModelDialog.py
  foqus_lib/gui/sdoe/updateSDOEModelDialog_UI.ui
Labels: SDOE
