Repository CCSI-Toolset/FOQUS, pull requests merged in 2019-04, with the labels that each got.

#464 Fix plugin search
  foqus_lib/framework/optimizer/BFGS.py
  foqus_lib/framework/optimizer/NLopt.py
  foqus_lib/framework/optimizer/OptCMA.py
  foqus_lib/framework/optimizer/PSUADE.py
  foqus_lib/framework/optimizer/SLSQP.py
  foqus_lib/framework/optimizer/Sample.py
  foqus_lib/framework/plugins/pluginSearch.py
  foqus_lib/framework/surrogate/ACOSSO.py
  foqus_lib/framework/surrogate/ALAMO.py
  foqus_lib/framework/surrogate/BSS-ANOVA.py
Labels: bug :bomb:

#470 Fixing some remote tubrine stuff
  foqus.py
  foqus_lib/framework/graph/graph.py
  foqus_lib/framework/sim/turbineConfiguration.py
  foqus_lib/framework/sim/turbineLiteDB.py
Labels: bug :bomb:

#468 Test Script Exit Code
  test/system_test/ui_test_01.py
Labels: Testing

#474 hiding Basic Data tab
  foqus_lib/gui/main/mainWindow.py
Labels: FOQUS GUI, SolventFit

#475 Delete Rosenbrock_no_vectors.foqus
  examples/UQ/Rosenbrock_no_vectors.foqus
Labels: Examples, UQ

#471 Updated the tutorial for remote turbine
  docs/source/chapt_flowsheet/figs/Anaconda_Prompt.jpg
  docs/source/chapt_flowsheet/figs/FOQUS_Folder.jpg
  docs/source/chapt_flowsheet/figs/RemoteSetting_New.jpg
  docs/source/chapt_flowsheet/figs/RemoteSetting_TurbineLite.jpg
  docs/source/chapt_flowsheet/figs/Remote_Flowsheet.jpg
  docs/source/chapt_flowsheet/tutorial/remote.rst
Labels: Documentation
