Repository CCSI-Toolset/FOQUS, pull requests merged in 2019-08, with the labels that each got.

#547 Fixing UQ bug related to scipy deprecation
  foqus_lib/framework/uq/ResponseSurfaces.py
Labels: UQ, bug :bomb:

#548 Update UncertaintyAnalysis.py
  foqus_lib/framework/uq/UncertaintyAnalysis.py
Labels: UQ, bug :bomb:

#549 Snobfit Plugin with examples
  docs/source/chapt_install/index.rst
  examples/Optimization/Snobfit_PR_Examples/Flash Example/Snobfit_Aspen_Optimization.bkp
  examples/Optimization/Snobfit_PR_Examples/Flash Example/Snobfit_Aspen_Optimization.json
  examples/Optimization/Snobfit_PR_Examples/Flash Example/Snobfit_Plugin_Aspen_Test.foqus
  examples/Optimization/Snobfit_PR_Examples/snobfit_plugin_test.foqus
  foqus_lib/framework/optimizer/Snobfit.py
Labels: Optimization

#559 Updating tutorials documentation
  docs/source/chapt_ouu/figs/1_OUUScreen.png
  docs/source/chapt_ouu/figs/2_OUUExample1.png
  docs/source/chapt_ouu/figs/3_OUUExample2.png
  docs/source/chapt_ouu/tutorial.rst
Labels: Documentation, OUU

#560 Documentation: Changed picture in optimization tutorial to show new code for objective function and constraint
  docs/source/chapt_opt/figs/Tutorial_Optimization_Objective.jpg
  docs/source/chapt_opt/figs/optProblemObj.svg
  docs/source/chapt_opt/tutorial/simple.rst
Labels: Documentation
