Repository CCSI-Toolset/FOQUS, pull requests merged in 2020-03, with the labels that each got.

#689 WIP Foqus gateway v2
  cloud/aws/Seal-VM.ps1
  cloud/aws/Set-Path.ps1
  cloud/aws/foqus_service.py
  cloud/aws/node/README.md
  cloud/aws/node/delete-simulation/package.json
  cloud/aws/node/foqus-fake-job-runner/package.json
  cloud/aws/node/foqus-sns-update/event_job_finished_number_underflow.json
  cloud/aws/node/foqus-sns-update/event_job_output_number_underflow.json
  cloud/aws/node/foqus-sns-update/events/event_job_setup.json
  cloud/aws/node/foqus-sns-update/events/event_job_submit.json
  cloud/aws/node/foqus-sns-update/index.js
  cloud/aws/node/foqus-sns-update/package.json
  cloud/aws/node/get-session-list/package.json
  cloud/aws/node/get-session-result-page/package.json
  cloud/aws/node/get-session/package.json
  cloud/aws/node/get-simulation-input-file/package.json
  cloud/aws/node/get-simulation-list/package.json
  cloud/aws/node/http-basic-authorizer/package.json
  cloud/aws/node/post-session-append/package.json
  cloud/aws/node/post-session-kill/package.json
  cloud/aws/node/post-session-result/package.json
  cloud/aws/node/post-session-start/package.json
  cloud/aws/node/post-simulation-signed-url/package.json
  cloud/aws/node/put-simulation-input/package.json
  cloud/aws/node/put-simulation-name/package.json
  foqus_lib/service/flowsheet.py
Labels: Priority:High

#690 Update UQ Tutorial 3
  docs/source/chapt_uq/tutorial/analysis.rst
Labels: Documentation, Priority:High, UQ

#692 Doc: Specified CSV file type for Optimization Tutorial #2 (parameter estimation)
  docs/source/chapt_opt/tutorial/parameter_est.rst
Labels: Priority:Mid

#693 Upoading csv samples to UQ tab - revised code
  foqus_lib/framework/uq/LocalExecutionModule.py
Labels: Priority:High

#691 Doc: Added Aspen versions in list of software SimSinter can handle
  docs/source/chapt_sinter/reference.rst
Labels: Priority:Mid

#694 Additional changes to foqus pyomo documentation
  docs/source/chapt_pyomo/tutorial/pyomo_test.rst
Labels: Priority:Mid

#695 Removing duplicate figures not used in docs
  docs/source/chapt_uq/figs/tutorial/Data Manipulation, Filtering Results.png
  docs/source/chapt_uq/figs/tutorial/Data ManipulationFiltering Results.png
Labels: Documentation, Priority:Mid

#697 Fix some sphix errors and improve layout
  docs/source/chapt_pyomo/tutorial/pyomo_test.rst
Labels: Documentation

#698 Build docs and check for errors
  .circleci/config.yml
  docs/Makefile
Labels: Documentation, Testing

#699 Fixing User Regression RS Validation Plugin
  foqus_lib/framework/surrogate/ALAMO.py
Labels: Priority:High

#700 pip install ccsi-foqus
  .circleci/config.yml
  .gitignore
  appveyor.yml
  docs/source/chapt_debug/index.rst
  foqus_lib/version/version.template
  requirements-dev.txt
  requirements.txt
  setup.py
Labels: Priority:High
