Repository CCSI-Toolset/FOQUS, pull requests merged in 2020-12, with the labels that each got.

#851 SDoE UI and plotting improvements
  foqus_lib/framework/sdoe/df_utils.py
  foqus_lib/framework/sdoe/distance.py
  foqus_lib/framework/sdoe/irsf.py
  foqus_lib/framework/sdoe/nusf.py
  foqus_lib/framework/sdoe/plot_utils.py
  foqus_lib/framework/sdoe/sdoe.py
  foqus_lib/framework/sdoe/usf.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
  foqus_lib/gui/sdoe/sdoePreview.py
  foqus_lib/gui/sdoe/sdoeSetupFrame.py
Labels: Priority:High, SDOE, enhancement

#834 Replace foqusPSUADEClient BAT file with entry point
  foqus_lib/gui/ouu/foqusPSUADEClient.bat
  foqus_lib/gui/ouu/foqusPSUADEClient.py
  foqus_lib/gui/ouu/ouuSetupFrame.py
  setup.py
Labels: Priority:Mid

#859 Foqus cloud notifications
  cloud/aws/README.md
  cloud/aws/foqus-websocket-app/.gitignore
  cloud/aws/foqus-websocket-app/README.md
  cloud/aws/foqus-websocket-app/onconnect/context.json
  cloud/aws/foqus-websocket-app/onconnect/event.json
  cloud/aws/foqus-websocket-app/onconnect/index.js
  cloud/aws/foqus-websocket-app/onconnect/package.json
  cloud/aws/foqus-websocket-app/ondisconnect/context.json
  cloud/aws/foqus-websocket-app/ondisconnect/event.json
  cloud/aws/foqus-websocket-app/ondisconnect/index.js
  cloud/aws/foqus-websocket-app/ondisconnect/package.json
  cloud/aws/foqus-websocket-app/sendmessage/context.json
  cloud/aws/foqus-websocket-app/sendmessage/event.json
  cloud/aws/foqus-websocket-app/sendmessage/index.js
  cloud/aws/foqus-websocket-app/sendmessage/package.json
  cloud/aws/foqus-websocket-app/status/context.json
  cloud/aws/foqus-websocket-app/status/event.json
  cloud/aws/foqus-websocket-app/status/index.js
  cloud/aws/foqus-websocket-app/status/package.json
  foqus_lib/framework/sim/turbineConfiguration.py
  foqus_lib/gui/help/helpBrowser.py
  foqus_lib/gui/help/helpBrowser_UI.ui
  setup.py
Labels: Priority:High

#863 SM Optimizer Improvements
  foqus_lib/framework/optimizer/SM_Optimizer.py
Labels: Optimization, Priority:High
