Repository CCSI-Toolset/FOQUS, pull requests merged in 2020-06, with the labels that each got.

#725 Alamo updates
  foqus_lib/framework/surrogate/ALAMO.py
Labels: Priority:High

#724 SDoE: Creating candidate documentation
  docs/source/chapt_sdoe/basics-uniform.rst
  docs/source/chapt_sdoe/creating-candidate.rst
  examples/tutorial_files/SDOE/surf1candidates.csv
Labels: Documentation, Priority:Mid, SDOE

#728 Switch to using mlrose-hiive rather than mlrose
  foqus_lib/framework/sdoe/order.py
  foqus_lib/framework/sdoe/test/test_order.py
  setup.py
Labels: Priority:High

#740 Adding a warning for node name convention
  foqus_lib/gui/flowsheet/drawFlowsheet.py
Labels: Priority:Mid

#744 New FOQUS test file for OUU using parallel computing on Cloud
  examples/test_files/OUU_Remote_Turbine_BFB/BFB_OUU_06_09_2020.foqus
  examples/test_files/OUU_Remote_Turbine_BFB/BFB_OUU_11_27_2019.foqus
Labels: OUU, Priority:High, enhancement

#747 cleaning up dialog
  foqus_lib/gui/sdoe/sdoeSetupFrame.py
Labels: FOQUS GUI, Priority:Mid, SDOE

#746 Keep docutils inline with what botocore requires
  requirements-dev.txt
Labels: Priority:Mid

#751 Note on packages needed when running on a VM
  docs/source/chapt_install/run_foqus.rst
Labels: Documentation, Priority:Mid

#750 Minor edits for Remote Turbine/AWS instructions
  docs/source/chapt_flowsheet/tutorial/remote.rst
Labels: Documentation, Priority:Mid

#748 FOQUS IDAES Example
  docs/source/chapt_idaes/figs/flowsheet.png
  docs/source/chapt_idaes/index.rst
  docs/source/chapt_idaes/tutorial/idaes_test.rst
  docs/source/chapt_idaes/tutorial/index.rst
  docs/source/index.rst
  examples/tutorial_files/IDAES/FOQUS_IDAES_Example.foqus
Labels: Priority:High

#753 Fixing a few GUI refresh issues
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog_UI.ui
  foqus_lib/gui/sdoe/sdoeSetupFrame.py
  foqus_lib/gui/uq/uqSetupFrame.py
Labels: FOQUS GUI, Priority:Mid, SDOE

#752 Creating a `foqus` an entry_point
  foqus_lib/foqus.py
  setup.py
Labels: FOQUS GUI, Priority:High

#755 Remove old foqus.py and reworked the batch file.
  appveyor.yml
  docs/source/chapt_install/index.rst
  docs/source/chapt_install/install_foqus.rst
  docs/source/chapt_install/run_foqus.rst
  foqus.py
  foqus_lib/foqus.py
  setup.py
Labels: Priority:High

#758 Checking pyomo model feasibility
  docs/source/chapt_pyomo/tutorial/pyomo_test.rst
  examples/tutorial_files/PYOMO/Pyomo_Test_Example.foqus
Labels: Priority:Mid

#757 Surrogate model based optimization solver
  docs/source/chapt_sm_optimizer/figs/alamo_settings.png
  docs/source/chapt_sm_optimizer/figs/alamo_settings_cont.png
  docs/source/chapt_sm_optimizer/figs/algorithm_steps.png
  docs/source/chapt_sm_optimizer/figs/flash_input_variables.png
  docs/source/chapt_sm_optimizer/figs/flash_output_variables.png
  docs/source/chapt_sm_optimizer/figs/flash_system.png
  docs/source/chapt_sm_optimizer/figs/framework_sm_optimizer.png
  docs/source/chapt_sm_optimizer/figs/mea_ccs.png
  docs/source/chapt_sm_optimizer/figs/obj_func_constraint.png
  docs/source/chapt_sm_optimizer/figs/run_alamo.png
  docs/source/chapt_sm_optimizer/figs/select_optim_vars.png
  docs/source/chapt_sm_optimizer/figs/sim_ensemble_generation.png
  docs/source/chapt_sm_optimizer/figs/sm_generation_data.png
  docs/source/chapt_sm_optimizer/figs/sm_optim_run.png
  docs/source/chapt_sm_optimizer/figs/sm_optimizer_options.png
  docs/source/chapt_sm_optimizer/figs/sm_var_select.png
  docs/source/chapt_sm_optimizer/index.rst
  docs/source/chapt_sm_optimizer/reference/SM_based_optimizer_introduction.rst
  docs/source/chapt_sm_optimizer/tutorial/SM_based_optimizer_tutorial.rst
  docs/source/index.rst
  examples/tutorial_files/SM_Optimizer/Flash_Optimization/Aspen_Flash_Model.json
  examples/tutorial_files/SM_Optimizer/Flash_Optimization/Automatic_Surrogate_Optimization_Flash_Tutorial_Images.foqus
  examples/tutorial_files/SM_Optimizer/Flash_Optimization/Flash_Optimization.bkp
  examples/tutorial_files/SM_Optimizer/Flash_Optimization/Flash_Optimization.foqus
  examples/tutorial_files/SM_Optimizer/MEA_Optimization/Automatic_Surrogate_Optimization_MEASSM_Working_minSRD.foqus
  examples/tutorial_files/SM_Optimizer/MEA_Optimization/CCSIMEAModel2_Updated.json
  examples/tutorial_files/SM_Optimizer/MEA_Optimization/CCSI_MEAModel2.bkp
  examples/tutorial_files/SM_Optimizer/MEA_Optimization/ccsi.opt
  foqus_lib/framework/optimizer/SM_Optimizer.py
  foqus_lib/framework/surrogate/ALAMO.py
Labels: Priority:High

#756 Fixing NUSF include column feature
  foqus_lib/framework/sdoe/df_utils.py
  foqus_lib/framework/sdoe/distance.py
  foqus_lib/framework/sdoe/nusf.py
  foqus_lib/framework/sdoe/plot_utils.py
  foqus_lib/framework/sdoe/sdoe.py
  foqus_lib/framework/sdoe/usf.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
  foqus_lib/gui/sdoe/sdoePreview.py
  foqus_lib/gui/sdoe/sdoeSetupFrame_UI.ui
Labels: Priority:High, SDOE

#761 Fix icons_rc and shortcut icon
  foqus_lib/foqus.py
  foqus_lib/gui/flowsheet/dataBrowserDialog_UI.ui
  foqus_lib/gui/flowsheet/dataFilterDialog_UI.ui
  foqus_lib/gui/flowsheet/edgePanel_UI.ui
  foqus_lib/gui/flowsheet/flowsheetSettingsDialog_UI.ui
  foqus_lib/gui/flowsheet/nodePanel_UI.ui
  foqus_lib/gui/foqus.ico
  foqus_lib/gui/help/helpBrowser_UI.ui
  foqus_lib/gui/main/Dash_UI.ui
  foqus_lib/gui/main/sessionDescriptionEdit_UI.ui
  foqus_lib/gui/main/settingsFrame_UI.ui
  foqus_lib/gui/main/turbineConfig_UI.ui
  foqus_lib/gui/make_shortcut.py
  foqus_lib/gui/model/dmfUploadDialog_UI.ui
  foqus_lib/gui/model/gatewayUploadDialog_UI.ui
  foqus_lib/gui/optimization/optMonitor_UI.ui
  foqus_lib/gui/optimization/optSampleGenDialog_UI.ui
  foqus_lib/gui/optimization/optSetupFrame_UI.ui
  foqus_lib/gui/surrogate/surrogateFrame_UI.ui
  icons_rc.py
  setup.py
Labels: Priority:High

#764 Only import TurbineDB on Windows.
  foqus_lib/framework/sim/turbineConfiguration.py
Labels: Priority:High
