Repository CCSI-Toolset/FOQUS, pull requests merged in 2020-11, with the labels that each got.

#841 https://github.com/CCSI-Toolset/FOQUS/issues/840
  cloud/aws/foqus_worker.py
  setup.py
Labels: Priority:High

#847 ipopt installation instructions
  docs/source/chapt_pyomo/tutorial/pyomo_test.rst
  docs/source/chapt_sm_optimizer/reference/SM_based_optimizer_introduction.rst
Labels: Priority:High

#845 GAMS solvers working in SM Optimizer
  foqus_lib/framework/optimizer/SM_Optimizer.py
Labels: Priority:Mid

#849 Revert to find_packages() to find packages
  foqus_lib/framework/surrogate/acosso/__init__.py
  foqus_lib/framework/surrogate/bssanova/__init__.py
  setup.py
Labels: Priority:High

#803 Input-Response Filling (IRSF)
  examples/tutorial_files/SDOE/irsf_example.csv
  foqus_lib/framework/sdoe/irsf.py
  foqus_lib/framework/sdoe/nusf.py
  foqus_lib/framework/sdoe/plot_utils.py
  foqus_lib/framework/sdoe/sdoe.py
  foqus_lib/framework/sdoe/usf.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog_UI.ui
  foqus_lib/gui/sdoe/sdoeSetupFrame.py
  setup.py
Labels: Priority:High, SDOE
