Repository CCSI-Toolset/FOQUS, pull requests merged in 2020-04, with the labels that each got.

#703 Updates documentation on how to install FOQUS
  docs/source/chapt_dev/index.rst
  docs/source/chapt_flowsheet/reference/getting_started.rst
  docs/source/chapt_install/index.rst
  docs/source/chapt_install/install_foqus.rst
  docs/source/chapt_install/install_optional.rst
  docs/source/chapt_install/install_python.rst
  docs/source/chapt_install/run_foqus.rst
  docs/source/index.rst
Labels: Priority:High

#705 Foqus gateway v2: KeyError
  foqus_lib/service/flowsheet.py
Labels: Priority:High

#707 Fixing SDOE plotting
  foqus_lib/framework/sdoe/df_utils.py
  foqus_lib/framework/sdoe/plot_utils.py
Labels: Priority:High, SDOE

#711 Optimization samples csv file format
  docs/source/chapt_opt/figs/optim_csv_samples_format.png
  docs/source/chapt_opt/figs/optim_samplevars_csv.png
  docs/source/chapt_opt/tutorial/parameter_est.rst
Labels: Priority:Mid
