Repository CCSI-Toolset/FOQUS, pull requests merged in 2020-08, with the labels that each got.

#777 Pylint fixes for foqus_lib/foqus.py
  foqus_lib/foqus.py
Labels: Priority:High, Testing

#784 Delete testOUU.py
  foqus_lib/framework/ouu/testOUU.py
Labels: OUU, Priority:High, Testing

#788 Fix commandline optimzation
  examples/test_files/Optimization/Opt_Test_01.foqus
  foqus_lib/foqus.py
  foqus_lib/framework/optimizer/BFGS.py
  foqus_lib/framework/optimizer/NLopt.py
  foqus_lib/framework/optimizer/OptCMA.py
  foqus_lib/framework/optimizer/PSUADE.py
  foqus_lib/framework/optimizer/SLSQP.py
  foqus_lib/framework/optimizer/Snobfit.py
  foqus_lib/framework/optimizer/optimization.py
  foqus_lib/framework/optimizer/problem.py
Labels: Priority:High

#798 Add foqus cmd line test
  .circleci/config.yml
  appveyor.yml
Labels: Priority:Mid

#799 Add Python tests for command line optimization
  .circleci/config.yml
  foqus_lib/foqus.py
  foqus_lib/unit_test/test_foqus_main.py
Labels: Priority:Mid, Testing
