Repository CCSI-Toolset/FOQUS, pull requests merged in 2020-09, with the labels that each got.

#816 Add missing PyQt5 import in foqus_lib/framework/uq/SampleRefiner.py
  foqus_lib/framework/uq/SampleRefiner.py
Labels: Priority:Mid

#804 Pylint-specific configuration and directives to address false-positive errors
  .circleci/config.yml
  .pylint/foqus_transform.py
  .pylint/pylintrc
  foqus_lib/framework/optimizer/problem.py
  requirements-dev.txt
Labels: Priority:Mid

#808 pylint: add missing import
  foqus_lib/framework/listen/listen.py
Labels: Priority:Mid

#814 Refactor method args to get rid of pylint false-positive errors
  foqus_lib/framework/uq/Model.py
Labels: Priority:Mid

#789 Update docs with instructions on how to install examples from GitHub releases.
  docs/source/chapt_HI/tutorial/HI_test.rst
  docs/source/chapt_flowsheet/tutorial/data.rst
  docs/source/chapt_flowsheet/tutorial/files.rst
  docs/source/chapt_flowsheet/tutorial/index.rst
  docs/source/chapt_flowsheet/tutorial/recycle.rst
  docs/source/chapt_flowsheet/tutorial/remote.rst
  docs/source/chapt_flowsheet/tutorial/sim_flowsheet.rst
  docs/source/chapt_flowsheet/tutorial/simple_flowsheet.rst
  docs/source/chapt_idaes/tutorial/idaes_test.rst
  docs/source/chapt_install/index.rst
  docs/source/chapt_install/install_examples.rst
  docs/source/chapt_opt/tutorial/simple.rst
  docs/source/chapt_ouu/tutorial.rst
  docs/source/chapt_pyomo/tutorial/pyomo_test.rst
  docs/source/chapt_sdoe/examples.rst
  docs/source/chapt_sinter/tutorial/acm.rst
  docs/source/chapt_sinter/tutorial/ap.rst
  docs/source/chapt_sinter/tutorial/excel.rst
  docs/source/chapt_sinter/tutorial/gproms.rst
  docs/source/chapt_sm_optimizer/tutorial/SM_based_optimizer_tutorial.rst
  docs/source/chapt_surrogates/tutorial/acosso.rst
  docs/source/chapt_surrogates/tutorial/alamo.rst
  docs/source/chapt_surrogates/tutorial/bssanova.rst
  docs/source/chapt_surrogates/tutorial/uq_model.rst
  docs/source/chapt_uq/tutorial/analysis.rst
  docs/source/chapt_uq/tutorial/data.rst
  docs/source/chapt_uq/tutorial/inf.rst
  docs/source/chapt_uq/tutorial/rs.rst
  docs/source/chapt_uq/tutorial/sim.rst
  docs/source/conf.py
Labels: Documentation, Priority:High

#819 OptCMA traceback import
  foqus_lib/framework/optimizer/OptCMA.py
Labels: Priority:Mid

#791 Fix pylint errors due to PyQt imports for foqus_lib/gui
  foqus_lib/gui/flowsheet/calculatedColumns.py
  foqus_lib/gui/main/Dash.py
  foqus_lib/gui/main/sessionDescriptionEdit.py
  foqus_lib/gui/main/settingsFrame.py
Labels: Priority:Mid, Testing

#823 SDoE: Addressing usability study findings
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog_UI.ui
  foqus_lib/gui/sdoe/sdoePreview_UI.ui
  foqus_lib/gui/sdoe/sdoeSetupFrame.py
  foqus_lib/gui/sdoe/sdoeSetupFrame_UI.ui
  foqus_lib/gui/sdoe/updateSDOEModelDialog_UI.ui
Labels: FOQUS GUI, Priority:High, SDOE

#820 Address PyQt-related errors when initializing GUI in foqus_lib.foqus
  foqus_lib/foqus.py
  foqus_lib/unit_test/test_foqus_main.py
  pytest.ini
Labels: Priority:High, Testing

#806 pylint: add explicit imports to get rid of undefined symbol errors
  foqus_lib/framework/optimizer/SM_Optimizer.py
Labels: Priority:Mid

#822 Fixing pylint stuff
  foqus_lib/framework/uq/LocalExecutionModule.py
  foqus_lib/framework/uq/Plotter.py
Labels: Priority:Mid
