Repository CCSI-Toolset/FOQUS, pull requests merged in 2021-07, with the labels that each got.

#930 Fix docs typo
  docs/source/chapt_intro/index.rst
Labels: Documentation, UQ

#926 Websocket library issue 925
  foqus_lib/gui/help/helpBrowser.py
  setup.py
Labels: Priority:High

#918 Test Python 3.8 compatibility
  .github/workflows/nightlies.yml
  .github/workflows/tests.yml
  foqus_lib/framework/optimizer/OptSNOBFIT.py
  foqus_lib/framework/optimizer/Sample.py
  foqus_lib/framework/sim/turbineConfiguration.py
  foqus_lib/framework/uq/LocalExecutionModule.py
  setup.py
Labels: Priority:High

#919 Improve naming for GitHub Actions workflows and jobs
  .github/workflows/checks.yml
Labels: Priority:Normal

#933 Improvements for test coverage: config file for more accurate estimate, CodeCov support in GitHub
  .coveragerc
  .github/workflows/checks.yml
  .gitignore
  requirements-dev.txt
Labels: Priority:High
