Repository CCSI-Toolset/FOQUS, pull requests merged in 2021-03, with the labels that each got.

#884 Documentation: Update install optional software file
  docs/source/chapt_install/install_optional.rst
Labels: Documentation, PSUADE

#885 ALAMO tutorial corrections
  docs/source/chapt_surrogates/figs/Alamo_Method_Settings_1.png
  docs/source/chapt_surrogates/figs/Alamo_Method_Settings_2.png
  docs/source/chapt_surrogates/tutorial/alamo.rst
  setup.py
Labels: Priority:High

#892 Add GitHub Actions CI workflows
  .circleci/config.yml
  .github/actions/build-docs/action.yml
  .github/actions/pylint/action.yml
  .github/actions/setup-foqus/action.yml
  .github/workflows/nightlies.yml
  .github/workflows/tests.yml
  appveyor.yml
Labels: Testing, enhancement

#896 Disable pylint check for import error when running module as script
  foqus_lib/framework/optimizer/SM_Optimizer.py
Labels: Priority:High

#895 Update CI status badges in README
  README.md
Labels: Priority:High

#898 Removing import statement from SM_Optimizer.py
  foqus_lib/framework/optimizer/SM_Optimizer.py
Labels: Priority:Normal

#891 Implementing data imputation feature
  foqus_lib/framework/sdoe/odoeu.py
  foqus_lib/framework/sdoe/plot_utils.py
  foqus_lib/framework/sdoe/sdoe.py
  foqus_lib/framework/uq/LocalExecutionModule.py
  foqus_lib/framework/uq/RSAnalyzer.py
  foqus_lib/framework/uq/SampleData.py
  foqus_lib/gui/sdoe/odoeSimSetup.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
  foqus_lib/gui/sdoe/sdoePreview.py
  foqus_lib/gui/sdoe/sdoeSetupFrame.py
  foqus_lib/gui/sdoe/sdoeSetupFrame_UI.ui
  foqus_lib/gui/sdoe/sdoeSimSetup.py
Labels: Priority:High, SDOE
