Repository CCSI-Toolset/FOQUS, pull requests merged in 2021-04, with the labels that each got.

#876 Vector Variable Support - Python
  foqus_lib/framework/graph/graph.py
  foqus_lib/framework/graph/node.py
  foqus_lib/framework/graph/nodeVars.py
  foqus_lib/framework/optimizer/problem.py
  foqus_lib/framework/sampleResults/results.py
  foqus_lib/framework/sintervectorize/SinterFileVectorize.py
  foqus_lib/gui/flowsheet/nodePanel.py
  foqus_lib/gui/main/mainWindow.py
  foqus_lib/gui/sintervectorize/SinterVectorizeDialog.py
  foqus_lib/gui/sintervectorize/SinterVectorizeDialog_UI.ui
Labels: Priority:High

#900 Get RTDs to use full width of page
  docs/source/_static/schema.css
Labels: Documentation, Priority:Normal

#899 MATLAB-FOQUS-Interface
  docs/source/chapt_matlab/figs/CSTR.svg
  docs/source/chapt_matlab/figs/results.svg
  docs/source/chapt_matlab/figs/terminal_window_msg.png
  docs/source/chapt_matlab/figs/tutorial_1.png
  docs/source/chapt_matlab/figs/tutorial_2.png
  docs/source/chapt_matlab/figs/tutorial_3.png
  docs/source/chapt_matlab/figs/tutorial_4.png
  docs/source/chapt_matlab/figs/tutorial_5.png
  docs/source/chapt_matlab/figs/tutorial_6.png
  docs/source/chapt_matlab/figs/tutorial_7.png
  docs/source/chapt_matlab/figs/tutorial_8.png
  docs/source/chapt_matlab/figs/tutorial_9.png
  docs/source/chapt_matlab/index.rst
  docs/source/chapt_matlab/reference/matlab_foqus_intro.rst
  docs/source/chapt_matlab/tutorial/matlab_foqus_tutorial.rst
  docs/source/index.rst
  examples/tutorial_files/MATLAB-FOQUS/Tutorial_1/CSTR_Steady_Stat_Option_1.foqus
  examples/tutorial_files/MATLAB-FOQUS/Tutorial_1/CSTR_Steady_State.m
  examples/tutorial_files/MATLAB-FOQUS/Tutorial_2/CSTR_Steady_Stat_Option_2.foqus
  examples/tutorial_files/MATLAB-FOQUS/Tutorial_2/CSTR_Steady_State.m
  examples/tutorial_files/MATLAB-FOQUS/Tutorial_2/data.dat
  examples/tutorial_files/MATLAB-FOQUS/Tutorial_2/example_2_matlab_foqus.m
  examples/tutorial_files/MATLAB-FOQUS/Tutorial_2/matlab_foqus_script.m
  examples/tutorial_files/MATLAB-FOQUS/Tutorial_2/output.csv
  foqus_lib/framework/pymodel/matlab_fs.py
Labels: Flowsheet, Priority:High
