Repository CCSI-Toolset/FOQUS, pull requests merged in 2021-06, with the labels that each got.

#910 Make warnings failures for ReadTheDocs builds
  .readthedocs.yaml
  docs/Makefile
Labels: Documentation, Priority:Normal

#911 Update known issues
  docs/source/chapt_debug/index.rst
Labels: Documentation, Priority:Normal

#913 Documenting a note on calculated variables for surrogates
  docs/source/chapt_surrogates/reference.rst
Labels: Priority:Low

#920 Use INFO level if failing to import optional pyomo dependency in SM_Optimizer plugin
  foqus_lib/framework/optimizer/SM_Optimizer.py
Labels: Priority:High

#922 Adding missing dunder init files
  foqus_lib/framework/sintervectorize/__init__.py
  foqus_lib/gui/sintervectorize/__init__.py
Labels: Priority:High

#923 Adding missing dunder init files
  foqus_lib/framework/sintervectorize/__init__.py
  foqus_lib/gui/sintervectorize/__init__.py
Labels: Priority:High
