Repository CCSI-Toolset/FOQUS, pull requests merged in 2021-08, with the labels that each got.

#936 Address CI failures due to pip install job timeouts
  .github/actions/setup-foqus/action.yml
  .github/workflows/checks.yml
Labels: Priority:High

#937 Address failures in nightly builds for Python 3.8 on Windows
  .github/actions/setup-foqus/action.yml
  .github/workflows/checks.yml
  .github/workflows/nightlies.yml
  docs/source/chapt_dev/index.rst
  docs/source/chapt_install/index.rst
  docs/source/chapt_install/install_python.rst
Labels: Priority:High

#938 Fixing SDoE scaling
  foqus_lib/framework/sdoe/irsf.py
  foqus_lib/framework/sdoe/nusf.py
Labels: SDoE

#940 Adding Inverse Scale Candidate test
  foqus_lib/framework/sdoe/irsf.py
  foqus_lib/framework/sdoe/test/test_irsf.py
Labels: Testing, SDoE

#941 Address SyntaxWarnings in Python 3.8
  foqus_lib/framework/uq/Plotter.py
Labels: Priority:Normal

#942 Remove unneeded coveragepy package
  requirements-dev.txt
Labels: Priority:Normal

#916 Add GUI tests and test framework based on pytest-qt plugin
  .github/workflows/checks.yml
  .gitignore
  .pylint/pylintrc
  foqus_lib/conftest.py
  foqus_lib/foqus.py
  foqus_lib/framework/uq/RSInference.py
  foqus_lib/gui/tests/__init__.py
  foqus_lib/gui/tests/conftest.py
  foqus_lib/gui/tests/test_main_window.py
  foqus_lib/gui/tests/test_uq.py
  foqus_lib/gui/uq/uqSetupFrame.py
  foqus_lib/tests/test_foqus_main.py
  pytest.ini
  pytest_qt_extras.py
  requirements-dev.txt
  setup.py
Labels: Priority:High

#946 Fixing typo in LaTeX / PDF project name
  .readthedocs.yaml
  docs/source/conf.py
Labels: Documentation, Priority:Normal

#949 Fixing bug in IRSF
  foqus_lib/framework/sdoe/irsf.py
  foqus_lib/framework/sdoe/plot_utils.py
Labels: bug :bomb:, SDoE, Priority:High

#951 SM UQ Plugin Tutorial
  docs/source/chapt_surrogates/tutorial/uq_model.rst
Labels: Priority:Normal
