Repository CCSI-Toolset/FOQUS, pull requests merged in 2021-11, with the labels that each got.

#971 Removing Opt_Uncertain_Test_01.foqus
  examples/test_files/Optimization/Opt_Uncertain_Test_01.foqus
Labels: Priority:Normal

#976 Add docs section with steps to run FOQUS without a GUI
  .readthedocs.yaml
  docs/source/chapt_install/run_foqus.rst
Labels: Documentation, Priority:Normal

#979 Fixing issue #977
  foqus_lib/framework/uq/LocalExecutionModule.py
  foqus_lib/gui/sdoe/sdoeSetupFrame.py
Labels: SDoE, FOQUS GUI, Priority:High

#983 Fixing link to contributors
  README.md
Labels: Documentation, Priority:Normal

#984 Address `pip install` failures in nightlies GitHub Actions workflow
  .github/workflows/nightlies.yml
Labels: Priority:High
