Repository CCSI-Toolset/FOQUS, pull requests merged in 2021-02, with the labels that each got.

#862 pylint fixes (5 of 7) from #812
  foqus_lib/framework/sim/turbineConfiguration.py
Labels: Priority:Mid

#874 UQ: Fixing typo in UQ Tutorial 3
  docs/source/chapt_uq/tutorial/analysis.rst
Labels: Documentation, Priority:High, UQ

#871 pylint fixes home stretch
  .circleci/config.yml
  .pylint/pylintrc
  foqus_lib/framework/graph/node.py
  foqus_lib/framework/optimizer/optimization.py
  foqus_lib/framework/sampleResults/test/results_s3_test.py
  foqus_lib/framework/sdoe/sdoe.py
  foqus_lib/framework/sim/turbineConfiguration.py
  foqus_lib/framework/surrogate/surrogate.py
  foqus_lib/framework/uq/LocalExecutionModule.py
  foqus_lib/framework/uq/Plotter.py
  foqus_lib/gui/flowsheet/dataBrowserFrame.py
  foqus_lib/gui/flowsheet/runRowsDialog.py
  foqus_lib/gui/heatIntegration/heatIntegrationFrame.py
  foqus_lib/gui/help/helpBrowser.py
  foqus_lib/gui/main/mainWindow.py
  foqus_lib/gui/ouu/foqusPSUADEClient.py
  foqus_lib/gui/ouu/ouuSetupFrame.py
  foqus_lib/gui/sdoe/sdoeSetupFrame.py
  foqus_lib/gui/sdoe/sdoeSimSetup.py
  foqus_lib/gui/uq/SimSetup.py
  foqus_lib/gui/uq/uqSetupFrame.py
  foqus_lib/service/flowsheet.py
Labels: Priority:High

#867 Turbine AWS Configuration and Status Update
  foqus_lib/framework/session/session.py
  foqus_lib/framework/sim/turbineConfiguration.py
  foqus_lib/gui/help/helpBrowser.py
  foqus_lib/gui/help/helpBrowser_UI.ui
Labels: Priority:Mid

#879 Restoring clean version of scaling.xlsx
  examples/other_files/Scaling_Spreadsheet/scaling.xlsx
Labels: Priority:High
