Repository CCSI-Toolset/FOQUS, pull requests merged in 2022-09, with the labels that each got.

#1060 Fixing matplotlib deprecation of 'fig.canvas.set_window_title'
  foqus_lib/framework/sdoe/plot_utils.py
  foqus_lib/framework/uq/Plotter.py
  setup.py
Labels: UQ, SDoE, Priority:High

#1047 Update flowsheet_control_test for Turbine node tests and patches/mocks
  foqus_lib/conftest.py
  foqus_lib/framework/graph/node.py
  foqus_lib/service/test/flowsheet_control_test.py
  foqus_lib/unit_test/node_test.py
Labels: Priority:High

#1053 Loading sample from CSV file
  foqus_lib/gui/common/InputPriorTable.py
Labels: bug :bomb:, UQ, Priority:Normal

#1061 Nusf history fix
  foqus_lib/framework/sdoe/nusf.py
Labels: bug :bomb:
