Repository CCSI-Toolset/FOQUS, pull requests merged in 2022-10, with the labels that each got.

#1056 fixing SDoE setup frame plotting bug
  foqus_lib/framework/sdoe/plot_utils.py
Labels: bug :bomb:, SDoE, Priority:Normal

#1065 Update TurbineClient to 4.0.2
  setup.py
Labels: Priority:High

#1066 Update PyQt to 5.15
  setup.py
Labels: Priority:High

#1069 check for empty Node Vector Variables
  foqus_lib/service/flowsheet.py
Labels: Priority:High

#1071 Document Update
  docs/source/chapt_flowsheet/reference/flowsheet.rst
  docs/source/chapt_flowsheet/reference/home.rst
  docs/source/chapt_flowsheet/reference/settings.rst
  docs/source/chapt_flowsheet/tutorial/remote.rst
  docs/source/chapt_install/install_optional.rst
  docs/source/chapt_intro/index.rst
  docs/source/chapt_ouu/reference.rst
  docs/source/chapt_sinter/tutorial/acm.rst
  docs/source/chapt_uq/tutorial/data.rst
Labels: Priority:Normal
