Repository CCSI-Toolset/FOQUS, pull requests merged in 2022-11, with the labels that each got.

#1067 Issue 1057
  foqus_lib/framework/sdoe/plot_utils.py
Labels: enhancement, Flowsheet, SDoE, Priority:Low

#1075 Fixing Plugin Load Issue and Adding Plugin Tests
  foqus_lib/conftest.py
  foqus_lib/framework/plugins/pluginSearch.py
  foqus_lib/framework/session/session.py
  foqus_lib/framework/surrogate/surrogate.py
  foqus_lib/gui/tests/test_plugins.py
Labels: Priority:High

#1068 FOQUSCloud lambda node16 update
  cloud/aws/node/delete-simulation/index.js
  cloud/aws/node/delete-simulation/package.json
  cloud/aws/node/dynamo-stream-trigger/index.js
  cloud/aws/node/dynamo-stream-trigger/package.json
  cloud/aws/node/foqus-fake-job-runner/index.js
  cloud/aws/node/foqus-fake-job-runner/package.json
  cloud/aws/node/foqus-fake-job-runner/running.js
  cloud/aws/node/foqus-fake-job-runner/setup.js
  cloud/aws/node/foqus-fake-job-runner/submit.js
  cloud/aws/node/foqus-sns-update/package.json
  cloud/aws/node/get-session-list/package.json
  cloud/aws/node/get-session-result-page/package.json
  cloud/aws/node/get-session/package.json
  cloud/aws/node/get-simulation-input-file/package.json
  cloud/aws/node/get-simulation-list/package.json
  cloud/aws/node/http-basic-authorizer/index.js
  cloud/aws/node/http-basic-authorizer/package.json
  cloud/aws/node/post-session-append/index.js
  cloud/aws/node/post-session-append/package.json
  cloud/aws/node/post-session-create/index.js
  cloud/aws/node/post-session-create/package.json
  cloud/aws/node/post-session-kill/index.js
  cloud/aws/node/post-session-kill/package.json
  cloud/aws/node/post-session-result/index.js
  cloud/aws/node/post-session-result/package.json
  cloud/aws/node/post-session-start/index.js
  cloud/aws/node/post-session-start/package.json
  cloud/aws/node/post-session-stop/index.js
  cloud/aws/node/post-session-stop/package.json
  cloud/aws/node/post-simulation-signed-url/package.json
  cloud/aws/node/put-simulation-input/package.json
  cloud/aws/node/put-simulation-name/package.json
Labels: Priority:Normal

#1081 Support For PyTorch Neural Network Models
  .github/workflows/checks.yml
  docs/source/chapt_surrogates/mlaiplugin.rst
  docs/source/references.rst
  examples/other_files/ML_AI_Plugin/Other_MLAI_Models/mea_column_model_customnormform_pytorch.pt
  examples/other_files/ML_AI_Plugin/mea_column_model.py
  examples/other_files/ML_AI_Plugin/mea_column_model_customnormform.py
  examples/other_files/ML_AI_Plugin/mea_column_model_customnormform_json.py
  examples/other_files/ML_AI_Plugin/mea_column_model_customnormform_savedmodel.py
  examples/other_files/ML_AI_Plugin/mea_column_model_training_customnormform.py
  examples/other_files/ML_AI_Plugin/mea_column_model_training_customnormform_json.py
  examples/other_files/ML_AI_Plugin/mea_column_model_training_customnormform_pytorch.py
  examples/other_files/ML_AI_Plugin/mea_column_model_training_customnormform_savedmodel.py
  foqus_lib/conftest.py
  foqus_lib/framework/graph/node.py
  foqus_lib/framework/ml_ai_models/mlaiSearch.py
  foqus_lib/gui/tests/test_ml_ai.py
  foqus_lib/unit_test/node_test.py
Labels: Priority:High

#1086 Address issues related to pywin32 v305
  .github/workflows/nightlies.yml
  setup.py
Labels: Priority:High
