Repository CCSI-Toolset/FOQUS, pull requests merged in 2023-11, with the labels that each got.

#1175 Add NLOpt installation instructions back
  docs/source/chapt_install/install_optional.rst
Labels: Priority:Normal

#1173 Pin pywin32 version to 306 to address #1172 and remove support for Python 3.7
  .github/actions/setup-foqus/action.yml
  .github/workflows/checks.yml
  .github/workflows/nightlies.yml
  docs/source/chapt_dev/index.rst
  docs/source/chapt_install/index.rst
  docs/source/chapt_install/install_python.rst
  setup.py
Labels: Priority:High

#1171 SDoE: embedding SDoE plots into QDialog windows
  foqus_lib/framework/sdoe/plot_utils.py
  foqus_lib/framework/sdoe/test/results_irsf.json
  foqus_lib/framework/sdoe/test/results_nusf.json
  foqus_lib/framework/sdoe/test/test_plot_utils.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog_UI.ui
  foqus_lib/gui/sdoe/sdoePreview.py
  foqus_lib/gui/sdoe/sdoePreview_UI.ui
  foqus_lib/gui/sdoe/sdoeSetupFrame.py
  foqus_lib/gui/tests/test_sdoe.py
Labels: SDoE, Priority:High
