Repository CCSI-Toolset/FOQUS, pull requests merged in 2023-04, with the labels that each got.

#1128 SDoE: update ODoE tutorials
  docs/source/chapt_odoe/figs/10_ODoE_outputSetup.png
  docs/source/chapt_odoe/figs/10b_ODoE_outputSetup.png
  docs/source/chapt_odoe/figs/13_ODoE_RSConfirmed.png
  docs/source/chapt_odoe/figs/13b_ODoE_RSConfirmed.png
  docs/source/chapt_odoe/figs/14_ODoE_PSUADErunning.png
  docs/source/chapt_odoe/figs/15_ODoE_resultsWindow.png
  docs/source/chapt_odoe/figs/16_ODoE_ResultsFile.png
  docs/source/chapt_odoe/figs/2_ODoE_main.png
  docs/source/chapt_odoe/figs/3b_ODoE_LoadRSTrainData.png
  docs/source/chapt_odoe/figs/4_ODoE_inputSetup.png
  docs/source/chapt_odoe/figs/7a_ODoE_LoadCand1.png
  docs/source/chapt_odoe/figs/7b_ODoE_CandGeneration0.png
  docs/source/chapt_odoe/figs/8a_ODoE_LoadCand2.png
  docs/source/chapt_odoe/figs/9_ODoE_CandGenerated.png
  docs/source/chapt_odoe/figs/9a-1_ODoE_LoadEval.png
  docs/source/chapt_odoe/figs/9a-2_ODoE_Cand&EvalSets.png
  docs/source/chapt_odoe/figs/9b_ODoE_Cand&EvalSets.png
  docs/source/chapt_odoe/tutorial-createcand.rst
  docs/source/chapt_odoe/tutorial-loadcand.rst
Labels: SDoE, Documentation, ODoE

#1129 UQ: Fixing slider for CDF and 3D plots
  foqus_lib/framework/uq/Plotter.py
Labels: UQ, Examples, Priority:High

#1138 Fix broken link in Install Optional Software docs
  docs/source/chapt_install/install_optional.rst
Labels: Priority:Normal

#1133 Set psuade default location with shutil
  foqus_lib/framework/session/session.py
Labels: Priority:Normal

#1137 Boverhof.user plugins backend.2023.03.09
  cloud/aws/node/put-simulation-input/index.js
  cloud/aws/node/put-simulation-name/index.js
  foqus_lib/service/flowsheet.py
Labels: Priority:High, FOQUS Cloud

#1140 Update intersphinx_mapping to non-deprecated format
  docs/source/conf.py
Labels: Documentation, Priority:High
