Repository CCSI-Toolset/FOQUS, pull requests merged in 2023-03, with the labels that each got.

#1115 Added sdoe tests
  docs/source/conf.py
  foqus_lib/framework/sdoe/test/__init__.py
  foqus_lib/framework/sdoe/test/candidates_irsf.csv
  foqus_lib/framework/sdoe/test/candidates_nusf.csv
  foqus_lib/framework/sdoe/test/candidates_usf.csv
  foqus_lib/framework/sdoe/test/config_irsf.ini
  foqus_lib/framework/sdoe/test/config_nusf.ini
  foqus_lib/framework/sdoe/test/config_usf.ini
  foqus_lib/framework/sdoe/test/test_distance.py
  foqus_lib/framework/sdoe/test/test_irsf.py
  foqus_lib/framework/sdoe/test/test_nusf.py
  foqus_lib/framework/sdoe/test/test_sdoe.py
  foqus_lib/framework/sdoe/test/test_usf.py
Labels: Priority:High

#1124 Add pre-commit configuration
  .pre-commit-config.yaml
  docs/source/chapt_dev/index.rst
  requirements-dev.txt
Labels: Priority:Normal

#1109 sdoe Test USF
  cloud/aws/node/foqus-sns-update/index.js
  cloud/aws/sdoe/lambda/lambda_function.py
  docs/source/chapt_sdoe/examples-uniform.rst
  docs/source/chapt_sdoe/figs/Ex1U_3_mM_choices.png
  foqus_lib/conftest.py
Labels: Priority:High

#1123 Introduced hypothesis testing
  foqus_lib/framework/sdoe/distance.py
  foqus_lib/framework/sdoe/test/test_distance.py
  requirements-dev.txt
Labels: Priority:Normal

#1096 SDoE: Implementing previous data into IRSF
  foqus_lib/framework/sdoe/distance.py
  foqus_lib/framework/sdoe/irsf.py
  foqus_lib/framework/sdoe/nusf.py
  foqus_lib/framework/sdoe/plot_utils.py
  foqus_lib/framework/sdoe/sdoe.py
  foqus_lib/framework/sdoe/test/test_irsf.py
  foqus_lib/framework/sdoe/test/test_nusf.py
  foqus_lib/framework/sdoe/test/test_usf.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog_UI.ui
  foqus_lib/gui/sdoe/sdoeSimSetup.py
Labels: SDoE, Priority:High

#1118 Adding documentation for ACM/VBA workaround
  docs/source/chapt_sinter/figs/acm_vba/01_VBAcode.png
  docs/source/chapt_sinter/figs/acm_vba/02_nodesettings.png
  docs/source/chapt_sinter/index.rst
  docs/source/chapt_sinter/vba_acm.rst
Labels: Documentation, Priority:High

#1125 Add test file for SDoE plot_utils.py
  foqus_lib/framework/sdoe/test/test_plot_utils.py
Labels: Priority:Normal
