Repository CCSI-Toolset/FOQUS, pull requests merged in 2024-10, with the labels that each got.

#1243 Adding documentation for Aspen Configuration Panel
  docs/source/chapt_flowsheet/figs/nodeEditor_AspenConfig.png
  docs/source/chapt_flowsheet/reference/flowsheet.rst
  foqus_lib/gui/flowsheet/nodePanel_UI.ui
Labels: Flowsheet, Documentation, Priority:Normal

#1244 Limiting design size maximum
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
Labels: SDoE, FOQUS GUI, Priority:Normal

#1245 removing no longer used foqus settings figure from docs
  docs/source/chapt_install/figs/foqus-settings.png
Labels: Priority:Normal

#1246 Spelling and RTD build fixes for latest update of typos and sphinx_rtd_theme
  docs/source/conf.py
  examples/test_files/Smoke_Tests/fs_smoke_test.py
  examples/test_files/Smoke_Tests/optimization_smoke_test.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_BFGS.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_COBYLA.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_CRS2.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_DIRECT-L-RAND.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_DIRECT-L.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_DIRECT.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_ESCH.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_ISRES.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_NEWUOA.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_Nelder-Mead.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_OptCMA.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_PE.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_PRAXIS.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_PSUADE.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_SLSQP.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_Sbplx.py
  examples/test_files/Smoke_Tests/optimization_smoke_test_constraint.py
  examples/test_files/Smoke_Tests/smoke_test_01 - Full.py
  examples/test_files/Smoke_Tests/smoke_test_01.py
  examples/test_files/Smoke_Tests/uq_smoke_test_data_analysis.py
  examples/test_files/Smoke_Tests/uq_smoke_test_data_visualization.py
  examples/test_files/Smoke_Tests/uq_smoke_test_inference.py
  examples/test_files/Smoke_Tests/uq_smoke_test_input_importance.py
  examples/test_files/Smoke_Tests/uq_smoke_test_polynomial.py
  examples/test_files/Smoke_Tests/uq_smoke_test_response_surface_validation.py
  examples/test_files/Smoke_Tests/uq_smoke_test_response_surface_visualization.py
  examples/test_files/Smoke_Tests/uq_smoke_test_response_uq_analysis.py
  foqus_lib/gui/main/mainWindow.py
  test/system_test/ui_test_01.py
Labels: Priority:High

#1242 Foqus cloud
  cloud/aws/logging.yaml
  foqus_lib/core.py
  foqus_lib/foqus.py
  foqus_lib/framework/session/session.py
  foqus_lib/framework/sim/turbineConfiguration.py
  foqus_lib/framework/sim/turbineLiteDB.py
  foqus_lib/service/flowsheet.py
  setup.py
Labels: Priority:Normal
