Repository CCSI-Toolset/FOQUS, pull requests merged in 2024-03, with the labels that each got.

#1165 Enable support for Python 3.8 thru 3.12
  .github/actions/setup-foqus/action.yml
  .github/workflows/checks.yml
  docs/source/chapt_dev/index.rst
  docs/source/chapt_install/index.rst
  docs/source/chapt_install/install_python.rst
  foqus_lib/framework/ml_ai_models/mlaiSearch.py
  foqus_lib/framework/plugins/pluginSearch.py
  foqus_lib/framework/sim/turbineConfiguration.py
  foqus_lib/framework/uq/Plotter.py
  foqus_lib/gui/dialogs/variableBrowser.py
  foqus_lib/gui/flowsheet/drawFlowsheet.py
  foqus_lib/gui/ouu/ouuSetupFrame.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
  foqus_lib/gui/sdoe/sdoeSetupFrame.py
  foqus_lib/gui/tests/test_ouu.py
  requirements-dev.txt
  requirements-mlai.txt
  setup.py
Labels: Priority:High

#1204 update FOQUS documentation to include info on how to set paths for SimSinter and TurbineLite
  docs/source/chapt_install/install_optional.rst
Labels: Documentation, Priority:Normal

#1184 Adding type annotations to SDoE
  foqus_lib/framework/sdoe/df_utils.py
  foqus_lib/framework/sdoe/distance.py
  foqus_lib/framework/sdoe/irsf.py
  foqus_lib/framework/sdoe/nusf.py
  foqus_lib/framework/sdoe/plot_utils.py
  foqus_lib/framework/sdoe/sdoe.py
  foqus_lib/framework/sdoe/usf.py
Labels: SDoE, Priority:Normal

#1203 Add Turbine Configuration Section To Debugging Documentation
  docs/source/chapt_debug/index.rst
Labels: Documentation, Priority:Normal

#1194 SDoE: implementing input type dependent ordering capability
  foqus_lib/framework/sdoe/order.py
  foqus_lib/framework/sdoe/sdoe.py
  foqus_lib/framework/sdoe/test/config_irsf.ini
  foqus_lib/framework/sdoe/test/config_nusf.ini
  foqus_lib/framework/sdoe/test/config_usf.ini
  foqus_lib/framework/sdoe/test/test_order.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
  foqus_lib/gui/sdoe/sdoeAnalysisDialog_UI.ui
Labels: SDoE, Priority:High

#1208 A few more copyright year updates
  .addheader.yml
  .pylint/foqus_transform.py
  foqus_lib/help/html/license.html
  foqus_lib/version/version.template
Labels: Priority:High

#1210 Fixes for bugs related to SDOE in 3.21-rc
  foqus_lib/gui/sdoe/sdoeAnalysisDialog.py
  setup.py
Labels: Priority:High

#1215 Convert logging exception to warning on Dask get_client() failure
  foqus_lib/framework/sdoe/sdoe.py
Labels: SDoE, Priority:High, Dask
